# Site settings
title: John Mitchell
email: jlmitch5@ncsu.edu
description: > # this means to ignore newlines until "baseurl:"
  I am senior in Computer Science at NC State, graduating in
  December of 2014.  This site collects some of the cool web
  things I have done in the past few years.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jlmitch5.github.io" # the base hostname & protocol for your site
twitter_username: jlmitch5dev
github_username:  jlmitch5

# Build settings
markdown: kramdown
